folio-org/mod-bulk-operations

src/main/resources/swagger.api/bulk-operations.yaml
The api-doc tool was not expecting spaces in an identifier. Patched now, but takes time to roll out to Jenkins, so fixed here.
Also this is an initial PR so that branch-protection settings can be enabled:
https://dev.folio.org/guidelines/create-new-repo/#configuration-at-github
=> MODBULKOPS-1 Use a sensible operationId, no spaces

src/main/java/org/folio/bulkops/service/BulkOperationService.java
Fixes https://issues.folio.org/browse/MODEXPW-375  for mod-bulk-operations module
There were cases when incorrect headers were sent by feign client(for ex. headers related to another user). It was caused by the fact that folioExecutionContext wasn't passed to threads created by BulkOperationServices's ExecutorService. Since InheritableThreadLocal is used in folioExecutionContext, these child threads still were initialized with folioExecutionContext which was present upon their creation, but it was never cleaned up/updated. EnrichUrlAndHeadersClient takes headers from the thread local folioExecutionContext and adds them to feign request, so in such case it was using same cached values for all requests.
The fix is to pass folioExecutionContext to runnable task and clean it up in the end …
=> MODEXPW-375 pass folioExecutionContext to ExecutorService's threads

pom.xml, src/main/java/org/folio/bulkops/domain/bean/HoldingsRecord.java
[MODBULKOPS-85](https://issues.folio.org/browse/MODBULKOPS-85) - Expected errors are not populated for Holdings identifiers
Prevent case when the same holding record are processed like unchanged entity.
Improve equals() - method. …
=> MODBULKOPS-85 - Expected errors are not populated for Holdings identifiers

src/main/java/org/folio/bulkops/service/BulkOperationService.java, src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java
[MODBULKOPS-57](https://issues.folio.org/browse/MODBULKOPS-57) - Empty "File with updated records" is included in the list of files for downloading when no records have been successfully changed
Remove option to download the result file if no changes were made.
Check number of committed records and set link to the result file only if more than 0.
Ideally …
=> MODBULKOPS-57 - Empty "File with updated records" is included in the list of files for downloading when no records have been successfully changed

src/main/java/org/folio/bulkops/util/UnifiedTableHeaderBuilder.java
[MODBULKOPS-66](https://issues.folio.org/browse/MODBULKOPS-66) - TD - BulkOps: UnifiedTable header should be reflected from csv models
At he present moment headers in the csv file and preview page comes from different sources. Right way to populate it from csv models (user, item, holding) extracting names from Csv-binding annotations.
1) Existing logic for generating headers from preview page should be deleted
2) Corresponding names should be extracted from csv models
* Improved header builder logic
- What other modules will …
=> MODBULKOPS-66 - TD - BulkOps: UnifiedTable header should be reflected from csv models

pom.xml
https://issues.folio.org/browse/MODBULKOPS-109
Upgrade Spring Boot from 3.0.2 to 3.0.7.
The Spring Boot upgrade indirectly upgrades spring-webmvc from 6.0.4 to 6.0.9 fixing Improper Access Control: https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-3369852 https://nvd.nist.gov/vuln/detail/CVE-2023-20860
The Spring Boot upgrade indirectly upgrades spring-boot-autoconfigure from 3.0.2 to 3.0.7 fixing Denial of Service (DoS): https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKBOOT-5564390
The Spring Boot upgrade indirectly upgrades spring-boot-actuator-autoconfigure from 3.0.2 to 3.0.7 fixing Access Restriction Bypass: https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORKBOOT-5441321 https://nvd.nist.gov/vuln/detail/CVE-2023-20873
The Spring Boot upgrade indirectly …
=> MODBULKOPS-109: Spring Boot 3.0.7 fixing vulns for Orchid

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, src/main/resources/swagger.api/bulk-operations.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODBULKOPS-111 Use GitHub Workflows api-lint and api-schema-lint and api-doc

src/main/java/org/folio/bulkops/service/BulkOperationService.java, src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java
[MODBULKOPS-136](https://issues.folio.org/browse/MODBULKOPS-136) - Reduce impact of "No changes required" on "Are you sure?" form performance
The main reason for slowing down the "Are you sure?" form is to check the equality of the updated entities (users, items, holdings - In-app approach). This logic should be moved to the commit phase (UpdateProcessor) as it is logically consistent with the commit phase and will also prevent the form from slowing down.
* Improved logic
* Updated tests
- What other modules will these …
=> MODBULKOPS-136 - Reduce impact of "No changes required" on "Are you sure?" form performance

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/bulkops/controller/BulkOperationController.java, src/main/java/org/folio/bulkops/service/BulkOperationService.java, src/main/java/org/folio/bulkops/service/LogFilesService.java, src/main/resources/swagger.api/bulk-operations.yaml, src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java
[MODBULKOPS-112](https://issues.folio.org/browse/MODBULKOPS-112) - File deletion API for Bulk Operations
Endpoint to delete file by name and bulk operation id should be implemented.
* Added endpoint
* Added unit tests …
=> MODBULKOPS-112 - File deletion API for Bulk Operations

src/main/java/org/folio/bulkops/domain/bean/HoldingsRecord.java, src/main/java/org/folio/bulkops/domain/bean/Item.java, src/main/java/org/folio/bulkops/processor/HoldingsDataProcessor.java, src/main/java/org/folio/bulkops/processor/HoldingsUpdateProcessor.java, src/main/java/org/folio/bulkops/service/BulkOperationService.java, src/test/java/org/folio/bulkops/processor/HoldingsDataProcessorTest.java, src/test/java/org/folio/bulkops/processor/UpdateProcessorTest.java, src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java
[MODBULKOPS-126](https://issues.folio.org/browse/MODBULKOPS-126) - Apply to item records when item suppression status differs from holding record
Apply changes to the item records when their suppression status differs from holdings record and provide meaning full message to the user
* Updated holdings processor validator and commit logic 
- Do PRs exist for these …
=> MODBULKOPS-126 - Apply to item records when item suppression status differs from holding record

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/bulkops/client/HoldingsClient.java, src/main/java/org/folio/bulkops/client/SRSRecordsClient.java, src/main/java/org/folio/bulkops/domain/bean/Instance.java, src/main/java/org/folio/bulkops/processor/AbstractUpdateProcessor.java, src/main/java/org/folio/bulkops/processor/HoldingsUpdateProcessor.java, src/main/java/org/folio/bulkops/processor/InstanceDataProcessor.java, src/main/java/org/folio/bulkops/processor/InstanceUpdateProcessor.java, src/main/java/org/folio/bulkops/processor/ItemUpdateProcessor.java, src/main/java/org/folio/bulkops/processor/UpdateProcessor.java, src/main/java/org/folio/bulkops/processor/UserUpdateProcessor.java, src/main/java/org/folio/bulkops/service/BulkOperationService.java, src/main/java/org/folio/bulkops/service/RecordUpdateService.java, src/main/java/org/folio/bulkops/service/RuleService.java, src/main/java/org/folio/bulkops/util/Constants.java, src/main/java/org/folio/bulkops/util/RuleUtils.java, src/test/java/org/folio/bulkops/processor/UpdateProcessorTest.java, src/test/java/org/folio/bulkops/service/RecordUpdateServiceTest.java
[MODBULKOPS-196](https://issues.folio.org/browse/MODBULKOPS-196) -  Updating Suppress from discovery flag
Bulk update the value of Suppress from discovery flag in instance records
* Implemented logic …
=> MODBULKOPS-196 -  Updating Suppress from discovery flag

NEWS.md, descriptors/ModuleDescriptor-template.json
Work being done by @folio-org/bama in [mod-data-export-spring](https://github.com/folio-org/mod-data-export-spring/pull/270) and related modules necessitated a breaking change in the provided `data-export-spring` interface, bumping its version to `2.0`.  This breaking change has no impact on `mod-bulk-operations`; as such, we can safely update our `ModuleDescriptor` to support this new version.
> [!WARNING]
> This PR **must** be merged before https://github.com/folio-org/mod-data-export-spring/pull/270, otherwise the snapshot environment will break.
=> [UXPROD-3903] Support data-export-spring interface 2.0

src/main/java/org/folio/bulkops/processor/ItemsNotesUpdater.java, src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java
[MODBULKOPS-134](https://folio-org.atlassian.net/browse/MODBULKOPS-134) - Preserve the "Staff only" flag when change note type and duplicate note in Items Bulk Edit …
=> MODBULKOPS-134 - Preserve the "Staff only" flag when change note type and duplicate note in Items Bulk Edit

src/main/java/org/folio/bulkops/client/QueryClient.java, src/main/java/org/folio/bulkops/service/QueryService.java, src/test/java/org/folio/bulkops/service/QueryServiceTest.java
[MODBULKOPS-279](https://folio-org.atlassian.net/browse/MODBULKOPS-279) - FQM flow: tenant information populating
To verify if request for central tenant returns: 
- identifiers of instances associated with the central tenant
- identifiers of  holdings records from member tenant
- identifiers of items from member tenants
- identifiers of user records from central tenant. 
- Do PRs exist …
=> MODBULKOPS-279 - FQM flow: tenant information populating

src/main/java/org/folio/bulkops/client/HoldingsNoteTypeClient.java, src/main/java/org/folio/bulkops/controller/BulkOperationController.java, src/main/java/org/folio/bulkops/domain/bean/BulkOperationsEntity.java, src/main/java/org/folio/bulkops/domain/bean/ExtendedHoldingsRecord.java, src/main/java/org/folio/bulkops/domain/bean/ExtendedItem.java, src/main/java/org/folio/bulkops/domain/bean/HoldingsNote.java, src/main/java/org/folio/bulkops/domain/bean/HoldingsNoteType.java, src/main/java/org/folio/bulkops/domain/bean/Item.java, src/main/java/org/folio/bulkops/domain/bean/ItemNote.java, src/main/java/org/folio/bulkops/domain/bean/NoteType.java, src/main/java/org/folio/bulkops/domain/converter/HoldingsNoteListConverter.java, src/main/java/org/folio/bulkops/domain/entity/BulkOperation.java, src/main/java/org/folio/bulkops/processor/note/AbstractNoteProcessor.java, src/main/java/org/folio/bulkops/processor/note/HoldingsNotesProcessor.java, src/main/java/org/folio/bulkops/processor/note/ItemNoteProcessor.java, src/main/java/org/folio/bulkops/service/BulkOperationService.java, src/main/java/org/folio/bulkops/service/HoldingsReferenceService.java, src/main/java/org/folio/bulkops/service/ItemReferenceService.java, src/main/java/org/folio/bulkops/service/NoteTableUpdater.java, src/main/java/org/folio/bulkops/service/PreviewService.java, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/29-08-2024_add_used_tenants.sql, src/main/resources/db/changelog/changes/29-08-2024_add_used_tenants.xml, src/main/resources/swagger.api/schemas/bulk_operation_dto.json, src/main/resources/swagger.api/schemas/tenantNotePair.json, src/test/java/org/folio/bulkops/processor/note/HoldingsNotesProcessorTest.java, src/test/java/org/folio/bulkops/processor/note/ItemNoteProcessorTest.java, src/test/java/org/folio/bulkops/service/HoldingsNoteProcessorTest.java, src/test/java/org/folio/bulkops/service/NoteTableUpdaterTest.java, src/test/java/org/folio/bulkops/service/PreviewServiceTest.java
[MODBULKOPS-329](https://folio-org.atlassian.net/browse/MODBULKOPS-329) - Include tenantId in Item's and Holdings' Notes names in ECS 
In ECS environment, when the item or holdings record data is displayed from multiple member tenants to be edited in the central tenant, the the columns name and properties on the bulk edit form will need to include tenant identification so that they can be easily differentiated.
Added tenant id to note.
- Do JIRAs exist to update the impacted …
=> MODBULKOPS-329 - Include tenantId in Item's and Holdings' Notes names in ECS 

src/main/java/org/folio/bulkops/domain/entity/BulkOperationRuleDetails.java, src/main/java/org/folio/bulkops/exception/RuleValidationTenantsException.java, src/main/java/org/folio/bulkops/processor/AbstractDataProcessor.java, src/main/java/org/folio/bulkops/processor/FolioInstanceDataProcessor.java, src/main/java/org/folio/bulkops/processor/HoldingsDataProcessor.java, src/main/java/org/folio/bulkops/processor/ItemDataProcessor.java, src/main/java/org/folio/bulkops/processor/UserDataProcessor.java, src/main/java/org/folio/bulkops/processor/Validator.java, src/main/java/org/folio/bulkops/service/ConsortiaService.java, src/main/java/org/folio/bulkops/service/RuleService.java, src/main/java/org/folio/bulkops/util/Constants.java, src/main/resources/db/changelog/changelog-master.xml, src/main/resources/db/changelog/changes/20-09-2024_add_tenants_to_rules.sql, src/main/resources/db/changelog/changes/20-09-2024_add_tenants_to_rules.xml, src/main/resources/swagger.api/schemas/action.json, src/main/resources/swagger.api/schemas/bulk_operation_rule.json, src/test/java/org/folio/bulkops/BaseTest.java, src/test/java/org/folio/bulkops/processor/FolioInstanceDataProcessorTest.java, src/test/java/org/folio/bulkops/processor/HoldingsDataProcessorTest.java, src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java
[MODBULKOPS-334](https://folio-org.atlassian.net/browse/MODBULKOPS-334) - Preventing record update with values from different tenants 
In ECS environment, the user will be updating holdings and item records from multiple tenants.   Bulk edit should not allow to save the record that is associated with one tenant with locations that belong to another tenant. 
Add column to rule details to store tenants, change schema.
- Are the …
=> MODBULKOPS-334 - Preventing record update with values from different tenants 

descriptors/ModuleDescriptor-template.json
it's TMP solution, permissions should be removed when mod-search is removed from dependency to calculate used tenants
=> Add missed mod-search permissions

src/main/java/org/folio/bulkops/service/ErrorService.java, src/test/java/org/folio/bulkops/service/ErrorServiceTest.java
[MODBULKOPS-393](https://folio-org.atlassian.net/browse/MODBULKOPS-393) - Issues related to display errors from DI on Confirmation screen of bulk edit MARC fields
Add check for empty error.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
=> MODBULKOPS-393 - Issues related to display errors from DI on Confirmation screen of bulk edit MARC fields

src/main/java/org/folio/bulkops/domain/bean/GetParsedRecordsBatchRequestBody.java, src/main/java/org/folio/bulkops/service/SrsService.java
[MODBULKOPS-416](https://folio-org.atlassian.net/browse/MODBULKOPS-416) - MARC instances set as deleted cannot be previewed or updated.
To fix issue when deleted records aren't presented in response.
Using of extended API for /batch/parsed-records/fetch (https://folio-org.atlassian.net/browse/MODSOURCE-824)
Ideally all of the PRs involved in breaking …
=> MODBULKOPS-416 - MARC instances set as deleted cannot be previewed or updated

src/main/java/org/folio/bulkops/service/MarcUpdateService.java, src/test/java/org/folio/bulkops/service/MarcUpdateServiceTest.java
[MODBULKOPS-434](https://folio-org.atlassian.net/browse/MODBULKOPS-434) - For Bulk edit of MARC Instances Confirmation screen fails to display when no changes are required
When do bulk edit of MARC Instances and select fields/actions that do not require changes then after clicking “Commit changes“ the bulk operation job fails and error appears "Error deleting file: " 
Add check for null for path.
- Are the JIRAs under active …
=> MODBULKOPS-434 - For Bulk edit of MARC Instances Confirmation screen fails to display when no changes are required

src/main/resources/swagger.api/schemas/bulk_operation_dto.json, src/main/resources/swagger.api/schemas/error.json, src/main/resources/swagger.api/schemas/error_type.json, src/test/java/org/folio/bulkops/service/ErrorServiceTest.java
[MODBULKOPS-270](https://folio-org.atlassian.net/browse/MODBULKOPS-270) - Differentiate between errors and warnings (updating schema)
Covers schema changes in mod-bulk-operations. 
1. Error schema should be extended to support new error types [field - type, Enum: ERROR, WARNING] and name of failed field [field - field, String: field].
2. BulkOperation schema should be extended to support num of errors and warnings.
- Are the JIRAs …
=> MODBULKOPS-270 - Differentiate between errors and warnings (updating schema)

src/main/java/org/folio/bulkops/processor/marc/MarcInstanceUpdateProcessor.java, src/main/java/org/folio/bulkops/service/BulkOperationService.java, src/main/java/org/folio/bulkops/service/DataExportJobUpdateService.java, src/main/java/org/folio/bulkops/service/ErrorService.java, src/main/java/org/folio/bulkops/service/MarcUpdateService.java, src/main/java/org/folio/bulkops/service/QueryService.java, src/main/java/org/folio/bulkops/service/SrsService.java, src/main/java/org/folio/bulkops/util/Constants.java, src/test/java/org/folio/bulkops/processor/marc/MarcInstanceUpdateProcessorTest.java, src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java, src/test/java/org/folio/bulkops/service/ErrorServiceTest.java, src/test/java/org/folio/bulkops/service/QueryServiceTest.java, src/test/java/org/folio/bulkops/service/SrsServiceTest.java
[MODBULKOPS-377](https://folio-org.atlassian.net/browse/MODBULKOPS-377) - Create log with error message from another module
If the bulk edit operations request to other modules succeeds (status is 200) but the other module fails to respond (due to some internal error) the bulk edit job fails but the details of what went wrong are not preserved because  Bulk edit log contains only a file with identifiers of records that were used to trigger the bulk edit job.
Save error to a file and add the link to a bulk operation.
- What …
=> MODBULKOPS-377 - Create log with error message from another module

src/main/java/org/folio/bulkops/service/BulkOperationService.java, src/main/java/org/folio/bulkops/service/DataImportJobCompletionReceiverService.java, src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java, src/test/java/org/folio/bulkops/service/DataImportJobCompletionReceiverServiceTest.java
[MODBULKSOPS-467](https://folio-org.atlassian.net/browse/MODBULKOPS-467) - Errors on Confirmation screen are increasing over time for bulk edit of MARC Instances due to reoccurring event of DI job completion
environment the following behavior noticed: the number of errors on Confirmation screen and in file with Committing-Changes-Errors increased over time. This happened because event of DI job completion continued to come many times, and each time after that bulk edit asked for one more portion of errors from DI
* Added exception handler
If there are breaking changes, please …
=> MODBULKSOPS-467 - Errors on Confirmation screen are increasing over time for bulk edit of MARC Instances due to reoccurring event of DI job completion

descriptors/ModuleDescriptor-template.json
Follow-up PR to [PR#354](https://github.com/folio-org/mod-bulk-operations/pull/354) with missed configuration for Eureka platform.
=> MODBULKOPS-454 - Issue with data-import.splitconfig.get (adding Eureka-specific configuration)

src/main/resources/db/changelog/changes/19-08-2025_add_allowed_item_statuses_table_with_data.sql, src/test/java/org/folio/bulkops/repository/AllowedItemStatusesRepositoryTest.java, src/test/java/org/folio/bulkops/service/ItemReferenceServiceTest.java
[MODBULKOPS-536](https://folio-org.atlassian.net/browse/MODBULKOPS-536) - Migrate settings from mod-configuration to mod-settings
Allowed statuses for items settings should be stored inside module database.
* Updated migration script …
=> MODBULKOPS-536 - Migrate settings from mod-configuration to mod-settings

src/main/java/org/folio/bulkops/util/Constants.java, src/main/java/org/folio/bulkops/util/FqmContentFetcher.java, src/main/java/org/folio/bulkops/util/FqmKeys.java, src/test/java/org/folio/bulkops/util/FqmContentFetcherTest.java
[MODBULKOPS-540](https://folio-org.atlassian.net/browse/MODBULKOPS-540) - ECS - Filter out shadow users when querying in Central tenant
Bulk edit should not edit the shadow users when editing user records in the central tenant and those records should be filtered out when the user queries for users in the central tenant. 
* Updated FQM content fetcher logic
- Do PRs …
=> MODBULKOPS-540 - ECS - Filter out shadow users when querying in Central tenant

src/main/java/org/folio/bulkops/util/MarcCsvHelper.java, src/test/java/org/folio/bulkops/util/MarcCsvHelperOptionNotFoundTest.java, src/test/java/org/folio/bulkops/util/MarcCsvHelperTest.java, src/test/resources/files/marc_csv_empty_notes.csv
[MODBULKOPS-560](https://folio-org.atlassian.net/browse/MODBULKOPS-560) - Notes, Subject columns are populated with not removed values on .csv files when it is expected to be empty
Autotests found that when do bulk edit Instances with source MARC “Notes“ column in .csv file downloaded from “Are you sure“ form, Confirmation screen displays values that should not be displayed (going to be removed), find examples of actions below:
1.  find & remove subfield
2.  find & remove field
3.  remove all
The issue is reproduced only in case “Notes“ column is going to be empty for the record. Works as expected in case “Notes“ column is not going to be empty.
The same issue is reproduced for “Subject“ column.
Remove filter for empty string.
Before merging this PR, please go through the following list …
=> MODBULKOPS-560 - Notes, Subject columns are populated with not removed values on .csv files when it is expected to be empty

src/main/java/org/folio/bulkops/util/MarcCsvHelper.java
[MODBULKOPS-504](https://folio-org.atlassian.net/browse/MODBULKOPS-504) - Incorrect updates-preview .csv file is downloaded from "Logs" when note, subject are edited but changes are not applied
Make proposed changes CSV files to download the same for Are you sure? form and Confirmation screen.
Let user download marc CSV file (which is used in Are you sure?) in all cases.
- Do PRs exist for …
=> MODBULKOPS-504 - Made proposed changes files the same
