folio-org/mod-bulk-operations

Dockerfile
NEWS.md
PULL_REQUEST_TEMPLATE.md
README.md

[MODBULKOPS-1](https://issues.folio.org/browse/MODBULKOPS-1)  - Setup mod-bulk-operations module
Updating configuration and boilerplate files. …

MODBULKOPS-1 - Setup mod-bulk-operations module

---

src/main/resources/application.yml
src/test/resources/application.yml

[MODBULKOPS-16](https://issues.folio.org/browse/MODBULKOPS-16) - BulkOperationService- uploading files with identifiers
Follow-up commit to [PR#16](https://github.com/folio-org/mod-bulk-operations/pull/15)
Fix name of Kafka groups …

Kafka group name fix

---

descriptors/ModuleDescriptor-template.json

Upgrading Module Descriptor

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/client/BulkEditClient.java
src/main/java/org/folio/bulkops/configs/kafka/KafkaConfiguration.java
src/main/java/org/folio/bulkops/domain/bean/Job.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/resources/application.yml
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java
src/test/resources/application.yml

[MODBULKOPS-11](https://issues.folio.org/browse/MODBULKOPS-11) - BulkOperationController
BulkOperationController should utilize capabilities of the BulkOperationService. Controller should provide the following endpoints: [ControllerImplementationDetails.](https://wiki.folio.org/display/FOLIJET/Bulk+Operations+redesign#BulkOperationsredesign-BuklEditControllerimplementationdetails)
* Improved integration with data-export-spring
- Do JIRAs exist to update the …

MODBULKOPS-11 - BulkOperationController

---

descriptors/ModuleDescriptor-template.json

Rename content-update.collection.post to content-update.item.post

Update ModuleDescriptor permission

---

descriptors/ModuleDescriptor-template.json

bump up inventory version

---

src/main/java/org/folio/bulkops/processor/ItemDataProcessor.java
src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java

[MODBULKOPS-41](https://issues.folio.org/browse/MODBULKOPS-41) - "Item effective location" is not changed
* Improved item processing logic
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially …

MODBULKOPS-41 - "Item effective location" is not changed

---

descriptors/ModuleDescriptor-template.json

MODBULKOPS-20 update permissions

---

Dockerfile

Enable prometheus agent to enable JVM metrics in grafana

Enable prometheus agent

---

NEWS.md
pom.xml

[MODBULKOPS-35](https://issues.folio.org/browse/MODBULKOPS-35) - Release 1.0.0

MODBULKOPS-35 - Release 1.0.0

---

src/main/java/org/folio/bulkops/adapters/ItemUnifiedTableHeaderBuilder.java

MODBULKOPS-50 fix columns order for items

---

.dockerignore
.gitignore
Dockerfile
prometheus-jmx-config.yaml

RANCHER-621 Add config file for prometheus

---

descriptors/ModuleDescriptor-template.json

mod-bulk-operations: memory settings

---

src/main/resources/application.yml

MODBULKOPS-50 increase file limit

---

src/main/java/org/folio/bulkops/domain/converter/BoundWithTitlesConverter.java
src/main/java/org/folio/bulkops/domain/converter/CirculationNoteListConverter.java
src/main/java/org/folio/bulkops/domain/converter/ContributorListConverter.java
src/main/java/org/folio/bulkops/domain/converter/CustomFieldsConverter.java
src/main/java/org/folio/bulkops/domain/converter/DamagedStatusConverter.java
src/main/java/org/folio/bulkops/domain/converter/EffectiveCallNumberComponentsConverter.java
src/main/java/org/folio/bulkops/domain/converter/HoldingsNoteListConverter.java
src/main/java/org/folio/bulkops/domain/converter/HoldingsStatisticalCodeListConverter.java
src/main/java/org/folio/bulkops/domain/converter/ItemNoteListConverter.java
src/main/java/org/folio/bulkops/domain/converter/ReceivingHistoryConverter.java
src/main/java/org/folio/bulkops/domain/converter/ServicePointConverter.java
src/main/java/org/folio/bulkops/service/UserReferenceHelper.java
src/main/java/org/folio/bulkops/util/Utils.java
src/test/java/org/folio/bulkops/service/OpenCSVConverterTest.java
src/test/resources/files/bad_data_holding_record.json
src/test/resources/files/bad_data_item.json
src/test/resources/files/bad_data_user.json

[MODBULKOPS-71](https://issues.folio.org/browse/MODBULKOPS-71) - Handle bad data gracefully
If the record contains bad data, or the expected (required) data is missing in the records, the bulk edit may fail to process records. The bad data occurs often and bulk edit needs to be more robust to handle such cases gracefully.
* Improved processing logic
* Added unit tests
- Do PRs exist for …

MODBULKOPS-71 - Handle bad data gracefully

---

src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

[MODBULKOPS-61](https://issues.folio.org/browse/MODBULKOPS-61) - Reported "Completed" status instead of "Completed with errors"
* Improved logic to set correct operation status
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …

MODBULKOPS-61 - Reported "Completed" status instead of "Completed with errors"

---

pom.xml
src/main/java/org/folio/bulkops/service/DataExportJobUpdateReceiverService.java
src/main/java/org/folio/bulkops/service/DataExportJobUpdateService.java
src/test/java/org/folio/bulkops/BaseTest.java
src/test/java/org/folio/bulkops/service/DataExportJobUpdateServiceTest.java

FOLSPRINGB-95 message headers parsing bugfix

FOLSPRINGB-95 message headers parsing bugfix

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

Release 1.0.5

---

src/main/java/org/folio/bulkops/domain/bean/HoldingsRecord.java
src/main/java/org/folio/bulkops/domain/bean/Item.java
src/main/java/org/folio/bulkops/domain/bean/Personal.java
src/main/java/org/folio/bulkops/domain/bean/UnifiedTableCell.java
src/main/java/org/folio/bulkops/domain/bean/User.java
src/main/java/org/folio/bulkops/util/UnifiedTableHeaderBuilder.java

[MODBULKOPS-66](https://issues.folio.org/browse/MODBULKOPS-66) - TD - BulkOps: UnifiedTable header should be reflected from csv models
At he present moment headers in the csv file and preview page comes from different sources. Right way to populate it from csv models (user, item, holding) extracting names from Csv-binding annotations.
1) Existing logic for generating headers from preview page should be deleted
2) Corresponding names should be extracted from csv models
* Improved header creation logic to determine data type and visibility
If there are breaking changes, please **STOP** and consider …

MODBULKOPS-66 - TD - BulkOps: UnifiedTable header should be reflected from csv models

---

src/main/java/org/folio/bulkops/domain/entity/BulkOperation.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/java/org/folio/bulkops/service/DataExportJobUpdateService.java
src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/17-04-2023_bulk_operation_default_values.sql
src/main/resources/db/changelog/changes/17-04-2023_bulk_operation_default_values.xml
src/test/java/org/folio/bulkops/repository/BulkOperationRepositoryTest.java
src/test/java/org/folio/bulkops/service/DataExportJobUpdateServiceTest.java
src/test/java/org/folio/bulkops/service/ErrorServiceTest.java

[MODBULKOPS-94](https://issues.folio.org/browse/MODBULKOPS-94) - Incorrect sort order on the Logs screen
* Fixed bulk operation entity creation logic …

MODBULKOPS-94 - Incorrect sort order on the Logs screen

---

src/main/java/org/folio/bulkops/domain/converter/AddressesConverter.java
src/main/java/org/folio/bulkops/domain/converter/CustomFieldsConverter.java
src/main/java/org/folio/bulkops/domain/converter/DepartmentsConverter.java
src/main/java/org/folio/bulkops/domain/converter/PatronGroupConverter.java
src/main/java/org/folio/bulkops/processor/AbstractDataProcessor.java
src/main/java/org/folio/bulkops/processor/UpdatedEntityHolder.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/java/org/folio/bulkops/service/ErrorService.java
src/main/java/org/folio/bulkops/util/Utils.java
src/test/java/org/folio/bulkops/processor/HoldingsDataProcessorTest.java
src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java
src/test/java/org/folio/bulkops/processor/UserDataProcessorTest.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java
src/test/java/org/folio/bulkops/util/UtilsTest.java

[MODBULKOPS-65](https://issues.folio.org/browse/MODBULKOPS-65) - TD - BulkOps: handling CSV <-> Object exceptions …

MODBULKOPS-65 - TD - BulkOps: handling CSV <-> Object exceptions

---

src/main/java/org/folio/bulkops/domain/converter/DateTimeConverter.java

[MODBULKOPS-65](https://issues.folio.org/browse/MODBULKOPS-65) - BulkOps: handling CSV <-> Object exceptions …

MODBULKOPS-65 - updade datetime converter

---

src/main/java/org/folio/bulkops/client/AddressTypeClient.java
src/main/java/org/folio/bulkops/client/ConfigurationClient.java
src/main/java/org/folio/bulkops/client/CustomFieldsClient.java
src/main/java/org/folio/bulkops/client/DepartmentClient.java
src/main/java/org/folio/bulkops/client/GroupClient.java
src/main/java/org/folio/bulkops/client/HoldingsClient.java
src/main/java/org/folio/bulkops/client/ItemClient.java
src/main/java/org/folio/bulkops/client/LocationClient.java
src/main/java/org/folio/bulkops/client/ServicePointClient.java
src/main/java/org/folio/bulkops/client/UserClient.java
src/main/java/org/folio/bulkops/service/HoldingsReferenceService.java
src/main/java/org/folio/bulkops/service/ItemReferenceService.java
src/main/java/org/folio/bulkops/service/UserReferenceService.java
src/main/java/org/folio/bulkops/util/Constants.java
src/main/java/org/folio/bulkops/util/Utils.java
src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java
src/test/java/org/folio/bulkops/service/HoldingsReferenceHelperTest.java
src/test/java/org/folio/bulkops/service/ItemReferenceHelperTest.java
src/test/java/org/folio/bulkops/service/OpenCSVConverterTest.java
src/test/java/org/folio/bulkops/service/UserReferenceHelperTest.java
src/test/java/org/folio/bulkops/service/UserReferenceServiceTest.java

[MODBULKOPS-104](https://issues.folio.org/browse/MODBULKOPS-104) - Error parsing custom fields names with semicolon
Encode CQL query to prevent integration issues.
Encode query to UTF-8.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …

MODBULKOPS-104 - Error parsing custom fields names with semicolon

---

pom.xml
src/main/java/org/folio/bulkops/client/RemoteFileSystemClient.java
src/main/java/org/folio/bulkops/configs/RemoteRepositoryConfig.java
src/test/java/org/folio/bulkops/BaseTest.java
src/test/java/org/folio/bulkops/client/RemoteFileSystemClientTest.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

Reverts folio-org/mod-bulk-operations#91

Revert "Revert "MODBULKOPS-103 - change RemoteStorageWriter implementation""

---

src/main/java/org/folio/bulkops/domain/bean/Personal.java
src/main/java/org/folio/bulkops/domain/converter/DateWithoutTimeConverter.java
src/main/java/org/folio/bulkops/util/Constants.java
src/test/java/org/folio/bulkops/domain/converter/DateWithoutTimeConverterTest.java
src/test/java/org/folio/bulkops/service/OpenCSVConverterTest.java

MODBULKOPS-96 - Change birthdate displaying in CSV file in bulk edit

---

src/main/java/org/folio/bulkops/processor/ItemDataProcessor.java
src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/16-06-2023_add_set_false_action_type.sql
src/main/resources/db/changelog/changes/16-06-2023_add_set_false_action_type.xml
src/main/resources/db/changelog/changes/16-06-2023_add_set_true_action_type.sql
src/main/resources/db/changelog/changes/16-06-2023_add_set_true_action_type.xml
src/main/resources/swagger.api/schemas/update_action_type.json
src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java

[MODBULKOPS-117](https://issues.folio.org/browse/MODBULKOPS-117) - Update required data model for "Suppress from discovery" (Items) …

MODBULKOPS-117 - Update required data model for "Suppress from discovery" (Items)

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/client/RemoteFileSystemClient.java

Release - 1.0.6

---

src/main/java/org/folio/bulkops/processor/ItemDataProcessor.java
src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java

[MODBULKOPS-101](https://issues.folio.org/browse/MODBULKOPS-101) - Supported bulk edit action for item notes …

MODBULKOPS-101 - circ note remove improvement

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/controller/BulkOperationController.java
src/main/java/org/folio/bulkops/service/ListUsersService.java
src/main/resources/swagger.api/bulk-operations.yaml
src/main/resources/swagger.api/schemas/user.json
src/main/resources/swagger.api/schemas/users.json
src/test/java/org/folio/bulkops/controller/BulkOperationControllerTest.java
src/test/java/org/folio/bulkops/service/ListUsersServiceTest.java

[MODBULKOPS-127](https://issues.folio.org/browse/MODBULKOPS-127) - Add endpoint to get distinct list of users on Logs tab
In order to provide a quick way to identify bulk edit jobs executed by a specific user, a new endpoint should be introduced to provide a distinct list of users on Logs tab.
Add  /bulk-operations/list-users endpoint
Ideally all of the …

MODBULKOPS-127 - Add endpoint to get distinct list of users on Logs tab

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/client/RemoteFileSystemClient.java
src/main/java/org/folio/bulkops/controller/BulkOperationController.java
src/main/java/org/folio/bulkops/service/LogFilesService.java
src/main/resources/swagger.api/bulk-operations.yaml
src/test/java/org/folio/bulkops/controller/BulkOperationControllerTest.java
src/test/java/org/folio/bulkops/service/LogFilesServiceTest.java

[MODBULKOPS-112](https://issues.folio.org/browse/MODBULKOPS-112) - File deletion API for Bulk Operations
Endpoint to delete file by name and bulk operation id should be implemented.
* Implemented endpoint
* Added unit test …

MODBULKOPS-112 - File deletion API for Bulk Operations

---

src/main/java/org/folio/bulkops/service/ErrorService.java
src/test/java/org/folio/bulkops/service/ErrorServiceTest.java

MODBULKOPS-123: Differentiate file names with errors.

---

src/main/java/org/folio/bulkops/domain/bean/Item.java
src/main/java/org/folio/bulkops/repository/BulkOperationExecutionContentRepository.java
src/main/java/org/folio/bulkops/service/ErrorService.java

[MODBULKOPS-136](https://issues.folio.org/browse/MODBULKOPS-136) - Reduce impact of "No changes required" on "Are you sure?" form performance
The main reason for slowing down the "Are you sure?" form is to check the equality of the updated entities (users, items, holdings - In-app approach). This logic should be moved to the commit phase (UpdateProcessor) as it is logically consistent with the commit phase and will also prevent the form from slowing down.
* Improved error logging
- What other modules will these changes …

MODBULKOPS-136 - Reduce impact of "No changes required" on "Are you sure?" form performance

---

pom.xml
src/main/java/org/folio/bulkops/controller/BulkOperationController.java
src/main/java/org/folio/bulkops/service/ErrorService.java
src/main/java/org/folio/bulkops/service/ListUsersService.java
src/test/java/org/folio/bulkops/service/ErrorServiceTest.java
src/test/java/org/folio/bulkops/service/ListUsersServiceTest.java

[MODBULKOPS-105](https://issues.folio.org/browse/MODBULKOPS-105) - Migrate to folio-spring-support v7.0.0
Migrate to the new version folio-spring-support v7.0.0.
Maven dependency updating.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …

MODBULKOPS-105 - Migrate to folio-spring-support v7.0.0

---

src/main/java/org/folio/bulkops/service/LogFilesService.java

[MODBULKOPS-130](https://issues.folio.org/browse/MODBULKOPS-130) - Remove files generated by incompleted jobs after a given number of days
Sometimes the error prevents bulk edit jobs from completion and the ending date remains indefinitely empty.   For such jobs the purging of the files generated by bulk edit should occur after a configured number of days elapsed from the start date of the bulk edit job.
Apply start date if end date is null.
- Do JIRAs exist to update the …

MODBULKOPS-130 - Remove files generated by incompleted jobs after a given number of days

---

src/main/java/org/folio/bulkops/domain/bean/HoldingsRecord.java

[MODBULKOPS-153](https://issues.folio.org/browse/MODBULKOPS-153) - Provide additional details for Instance (Title, Publisher, Publication date) for holdings record
Provide information that is consistent with Holdings record display in Inventory.
* Renamed column Instance -> Instance (Title, Publisher, Publication date)
Ideally all of the PRs involved in …

MODBULKOPS-153 - Provide additional details for Instance (Title, Publisher, Publication date) for holdings record

---

pom.xml

[MODBULKOPS-156](https://issues.folio.org/browse/MODBULKOPS-156) - mod-bulk-operations: spring upgrade
folio-spring-base version to 7.2.0 (last released)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

MODBULKOPS-156 - mod-bulk-operations: spring upgrade

---

src/main/java/org/folio/bulkops/processor/HoldingsDataProcessor.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/java/org/folio/bulkops/util/Constants.java
src/test/java/org/folio/bulkops/processor/HoldingsDataProcessorTest.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java
src/test/java/org/folio/bulkops/service/DiscoverySuppressTestData.java

[MODBULKOPS-126](https://issues.folio.org/browse/MODBULKOPS-126) - Apply to item records when item suppression status differs from holding record
Apply changes to the item records when their suppression status differs from holdings record and provide meaning full message to the user
* Updated holdings commit logic
Ideally all of the …

MODBULKOPS-126 - Apply to item records when item suppression status differs from holding record

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/bulkops/configs/CustomFeignErrorDecoder.java
src/main/java/org/folio/bulkops/domain/bean/Personal.java
src/main/java/org/folio/bulkops/domain/bean/PreferredContactType.java
src/main/java/org/folio/bulkops/domain/converter/DepartmentsConverter.java
src/main/java/org/folio/bulkops/domain/converter/PreferredContactTypeIdConverter.java
src/main/java/org/folio/bulkops/service/ItemNoteTableUpdater.java
src/main/java/org/folio/bulkops/service/ItemReferenceService.java
src/main/java/org/folio/bulkops/service/UserReferenceHelper.java
src/main/java/org/folio/bulkops/service/UserReferenceService.java
src/main/java/org/folio/bulkops/util/Constants.java
src/test/java/org/folio/bulkops/configs/CustomFeignErrorDecoderTest.java
src/test/java/org/folio/bulkops/domain/converter/DepartmentsConverterTest.java
src/test/java/org/folio/bulkops/service/ItemNoteTableUpdaterTest.java

[MODBULKOPS-165](https://issues.folio.org/browse/MODBULKOPS-165) - [Release 1.1.1](mod-bulk-operations: module release)

MODBULKOPS-165 - Release 1.1.1

---

src/main/java/org/folio/bulkops/client/ItemClient.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

[MODBULKOPS-166](https://issues.folio.org/browse/MODBULKOPS-166) - Suppress Holdings from discovery: changes are applied to no more than 10 associated Items
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

MODBULKOPS-166 - Suppress Holdings from discovery: changes are applied to no more than 10 associated Items

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/client/ItemClient.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

[MODBULKOPS-167](https://issues.folio.org/browse/MODBULKOPS-167) - mod-bulk-operations: module release
Release v1.1.2.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

MODBULKOPS-167 - Release 1.1.2

---

NEWS.md
pom.xml

Release 1.1.3

---

NEWS.md
pom.xml

Release 1.1.4

---

pom.xml

MODBULKOPS-167 bump up folio-s3-client

---

NEWS.md
pom.xml

Release 1.1.5

---

NEWS.md
pom.xml

[MODBULKOPS-193](https://issues.folio.org/browse/MODBULKOPS-193) - mod-bulk-operations: module release
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

MODBULKOPS-193 - Release 1.1.7

---

src/main/java/org/folio/bulkops/service/NoteTableUpdater.java

MODBULKOPS-172: Update Item record column names. upd

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/client/InstanceStorageClient.java
src/main/java/org/folio/bulkops/domain/bean/Instance.java
src/main/java/org/folio/bulkops/processor/DataProcessorFactory.java
src/main/java/org/folio/bulkops/processor/InstanceDataProcessor.java
src/main/java/org/folio/bulkops/processor/InstanceUpdateProcessor.java
src/main/java/org/folio/bulkops/processor/UpdateProcessorFactory.java
src/test/java/org/folio/bulkops/BaseTest.java
src/test/java/org/folio/bulkops/processor/InstanceDataProcessorTest.java
src/test/java/org/folio/bulkops/processor/UpdateProcessorTest.java

[MODBULKOPS-195](https://issues.folio.org/browse/MODBULKOPS-195) - Updating Staff suppress flag
Bulk update the value of Staff suppress flag in instance records
* Implemented processors logic …

MODBULKOPS-195 - Updating Staff suppress flag

---

src/main/java/org/folio/bulkops/domain/bean/ContributorName.java
src/main/java/org/folio/bulkops/service/InstanceReferenceService.java
src/test/java/org/folio/bulkops/service/OpenCSVConverterTest.java

[MODBULKOPS-179](https://issues.folio.org/browse/MODBULKOPS-179) - Rendering Instance record data in bulk edit forms and files
Fixed contributor properties
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …

MODBULKOPS-179 - Rendering Instance record data in bulk edit forms and files

---

src/main/java/org/folio/bulkops/service/HoldingsReferenceService.java

[MODBULKOPS-196](https://issues.folio.org/browse/MODBULKOPS-196) -  Updating Suppress from discovery flag
* Improved holdings update logic …

MODBULKOPS-196 -  Updating Suppress from discovery flag

---

src/main/java/org/folio/bulkops/controller/BulkOperationController.java

https://issues.folio.org/browse/MODBULKOPS-217
Offset parameter on preview works incorrectly
Pass the offset param value from the controller into chain of methods invocation.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODBULKOPS-217: Offset parameter on preview works incorrectly

---

src/main/java/org/folio/bulkops/client/HoldingsNoteTypeClient.java
src/main/java/org/folio/bulkops/client/ItemNoteTypeClient.java
src/main/java/org/folio/bulkops/service/HoldingsReferenceService.java
src/main/java/org/folio/bulkops/service/ItemReferenceService.java
src/main/java/org/folio/bulkops/service/PreviewService.java
src/main/java/org/folio/bulkops/util/Constants.java
src/test/java/org/folio/bulkops/service/HoldingsReferenceHelperTest.java
src/test/java/org/folio/bulkops/service/ItemReferenceHelperTest.java
src/test/java/org/folio/bulkops/service/OpenCSVConverterTest.java
src/test/java/org/folio/bulkops/service/PreviewServiceTest.java

[MODBULKOPS-224](https://folio-org.atlassian.net/browse/MODBULKOPS-224) - Not all but up to 10 note types are displayed in Bulk edit
Not all but up to 10 note types are displayed in Bulk edit
Set limit=Integer.MAX for note types query. …

MODBULKOPS-224 - Not all but up to 10 note types are displayed in BulkEdit

---

pom.xml
src/main/java/org/folio/bulkops/client/QueryClient.java
src/main/java/org/folio/bulkops/service/QueryService.java
src/test/java/org/folio/bulkops/service/QueryServiceTest.java

[MODBULKOPS-229](https://folio-org.atlassian.net/browse/MODBULKOPS-229) - Improve logic to process changed getSortedIds response
QueryService logic should be changed to process getSortedIds response as per https://folio-org.atlassian.net/browse/MODFQMMGR-137
* Improved logic
Ideally all of the PRs involved in breaking changes would be …

MODBULKOPS-229 - Improve logic to process changed getSortedIds response

---

src/main/java/org/folio/bulkops/processor/ItemDataProcessor.java
src/main/java/org/folio/bulkops/util/Constants.java
src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java

https://folio-org.atlassian.net/browse/MODBULKOPS-203
Add The column "Holdings (Location, Call number)" in the preview of matching records
Bug fix.
Populate holdings data before a preview.
Fix the position of the notes because of the shift, caused by brand new field intro
Ideally all of the PRs involved in breaking changes would be merged in the same day …

MODBULKOPS-203: Provide data for Holdings column to Item record preview. Bug fix

---

src/main/java/org/folio/bulkops/domain/bean/Item.java
src/main/java/org/folio/bulkops/processor/ItemUpdateProcessor.java

[MODBULKOPS-203](https://folio-org.atlassian.net/browse/MODBULKOPS-203) - Provide data for Holdings column to Item record preview
* Updated item and itemUpdateProcessor logic
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODBULKOPS-203 - Provide data for Holdings column to Item record preview

---

pom.xml

https://folio-org.atlassian.net/browse/MODBULKOPS-238
spring upgrade
spring-boot-starter-parent -> 3.2.3
folio-spring-base -> 8.1.0
folio-spring-cql -> 8.1.0
hypersistence-utils-hibernate-63 -> 3.7.3 …

MODBULKOPS-238: spring upgrade

---

src/main/java/org/folio/bulkops/controller/BulkOperationController.java
src/main/java/org/folio/bulkops/domain/entity/BulkOperation.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/12-03-2024_add_user_friendly_query_field.sql
src/main/resources/db/changelog/changes/12-03-2024_add_user_friendly_query_field.xml
src/main/resources/swagger.api/schemas/query-request.json
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

[MODBULKOPS-237](https://folio-org.atlassian.net/browse/MODBULKOPS-237) - Extend bulk operation schema with additional field
It’s required add additional field to bulk operation schema. This field will be used to store user friendly value of query
* Added required field
Ideally all of the PRs involved in breaking changes would be …

MODBULKOPS-237 - Extend bulk operation schema with additional field

---

src/main/java/org/folio/bulkops/service/EntityTypeService.java

[MODBULKOPS-230](https://folio-org.atlassian.net/browse/MODBULKOPS-230) - FQM Integration - Instances
The module should support Instances entity type.
Improved EntityTypeService to support instances and holdings records types …

MODBULKOPS-230 - FQM Integration - Instances

---

NEWS.md
pom.xml

[MODBULKOPS-250](https://folio-org.atlassian.net/browse/MODBULKOPS-250) - mod-bulk-operations: module release …

MODBULKOPS-250 - Release 2.0.0

---

src/main/java/org/folio/bulkops/domain/bean/CustomFieldTypes.java
src/main/java/org/folio/bulkops/domain/converter/CustomFieldsConverter.java

Suport 'DATE_PICKER' custom type

---

src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

[MODBULKOPS-264](https://folio-org.atlassian.net/browse/MODBULKOPS-264) - Specific case when some records are missed in .csv file with updated records
The issue is detected on a specific dataset. Attached file can be used to reproduce the issue on bugfest environment (Quesnelia, Poppy). On Confirmation screen the number of changed records (actually updated) is greater than the number of records in the .csv file with updated records.
* Fixed csv writer logic
- Do JIRAs exist to …

MODBULKOPS-264 - Specific case when some records are missed in .csv file with updated records

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

Release 2.0.2

---

src/main/java/org/folio/bulkops/processor/ItemsNotesUpdater.java
src/main/java/org/folio/bulkops/util/Constants.java
src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java

https://folio-org.atlassian.net/browse/MODBULKOPS-257
Staff only Item notes
When a new note is added it might contain Staff only flag set to true.  If the flag is not provided the value is set to false.
Modification applies to Item notes, check-in, check-out notes only. …

MODBULKOPS-257: Staff only Item notes propagation

---

src/main/java/org/folio/bulkops/processor/HoldingsNotesUpdater.java
src/test/java/org/folio/bulkops/processor/HoldingsDataProcessorTest.java

https://folio-org.atlassian.net/browse/MODBULKOPS-258
Staff only Holdings notes
When a new note is added it might contain a Staff-only flag set to true. If the flag is not provided the value is set to false.
Administrative notes are not affected by this modification. …

MODBULKOPS-258: Staff only Holdings notes propagation

---

README.md
src/main/resources/application.yml

https://folio-org.atlassian.net/browse/MODBULKOPS-267
To increase multipart file size consumption, the brand new property spring.servlet.multipart.max-request-size should be introduced
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …

MODBULKOPS-267: Increase multipart upload consumption size

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/client/InstanceNoteTypesClient.java
src/main/java/org/folio/bulkops/domain/bean/Instance.java
src/main/java/org/folio/bulkops/domain/converter/InstanceNoteListConverter.java
src/main/java/org/folio/bulkops/processor/AdministrativeNotesUpdater.java
src/main/java/org/folio/bulkops/processor/InstanceDataProcessor.java
src/main/java/org/folio/bulkops/processor/InstanceNotesUpdaterFactory.java
src/main/java/org/folio/bulkops/service/InstanceReferenceHelper.java
src/main/java/org/folio/bulkops/service/InstanceReferenceService.java
src/main/java/org/folio/bulkops/service/NoteTableUpdater.java
src/main/java/org/folio/bulkops/service/PreviewService.java
src/main/java/org/folio/bulkops/util/Constants.java
src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/02-05-2024_add_instance_note_option_type.sql
src/main/resources/db/changelog/changes/02-05-2024_add_instance_note_option_type.xml
src/main/resources/swagger.api/bulk-operations.yaml
src/main/resources/swagger.api/schemas/instance_note_type.json
src/main/resources/swagger.api/schemas/instance_note_type_collection.json
src/main/resources/swagger.api/schemas/update_option_type.json
src/test/java/org/folio/bulkops/processor/InstanceDataProcessorTest.java
src/test/java/org/folio/bulkops/service/PreviewServiceTest.java

[MODBULKOPS-242](https://folio-org.atlassian.net/browse/MODBULKOPS-242) - Supported Bulk Edit Actions for FOLIO Instance Notes
Provide functionality bulk updating FOLIO instances' notes.
* Implemented notes editing logic
* Added unit tests
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

MODBULKOPS-242 - Supported Bulk Edit Actions for FOLIO Instance Notes

---

src/main/java/org/folio/bulkops/service/ErrorService.java
src/test/java/org/folio/bulkops/service/ErrorServiceTest.java

[MODBULKOPS-268](https://folio-org.atlassian.net/browse/MODBULKOPS-268) - Timeout executing PUT error not recorded in Errors
If the job completes with errors, the errors are saved in the file that is available for the download from the Action menu and Logs
Replace cql repository.
Ideally all of the PRs involved in breaking changes would be merged in the …

MODBULKOPS-268 - Timeout executing PUT error not recorded in Errors

---

src/main/java/org/folio/bulkops/domain/bean/BulkOperationsEntity.java
src/main/java/org/folio/bulkops/domain/bean/HoldingsRecord.java
src/main/java/org/folio/bulkops/domain/bean/Instance.java
src/main/java/org/folio/bulkops/domain/bean/Item.java
src/main/java/org/folio/bulkops/domain/bean/User.java
src/main/java/org/folio/bulkops/exception/OptimisticLockingException.java
src/main/java/org/folio/bulkops/service/RecordUpdateService.java
src/main/java/org/folio/bulkops/util/Constants.java
src/test/java/org/folio/bulkops/service/RecordUpdateServiceTest.java

[MODBULKOPS-256](https://folio-org.atlassian.net/browse/MODBULKOPS-256) - Provide User-friendly Error Message for Optimistic Locking in Downloaded Errors.
Provide user-friendly error that will notify the user about the version conflict when saving updates.
RecordUpdateService should contain logic for resolving and saving needed error.
Ideally all of the …

MODBULKOPS-256 - Provide User-friendly Error Message for Optimistic Locking in Downloaded Errors.

---

src/main/java/org/folio/bulkops/domain/bean/HoldingsRecord.java
src/main/java/org/folio/bulkops/domain/converter/BulkOperationsEntityCsvWriter.java
src/main/java/org/folio/bulkops/service/HoldingsReferenceHelper.java
src/main/java/org/folio/bulkops/service/PreviewService.java
src/main/java/org/folio/bulkops/util/Constants.java
src/test/java/org/folio/bulkops/service/OpenCSVConverterTest.java
src/test/java/org/folio/bulkops/service/PreviewServiceTest.java

MODBULKOPS-227 - Holdings record's column names cleanup
Currently the list of column names for holdings records is ordered almost randomly and it includes properties that are important for backend processes but are normally not exposed in the inventory UI.
* Updated holdings record fields and mapping logic
Ideally all of the PRs …

MODBULKOPS-227 - Holdings record's column names cleanup

---

src/main/java/org/folio/bulkops/controller/BulkOperationController.java
src/main/java/org/folio/bulkops/domain/entity/BulkOperationDataProcessing.java
src/main/java/org/folio/bulkops/repository/BulkOperationDataProcessingRepository.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/24-05-2024_drop_id_column_bulk_operation_data_processing.sql
src/main/resources/db/changelog/changes/24-05-2024_drop_id_column_bulk_operation_data_processing.xml
src/test/java/org/folio/bulkops/repository/BulkOperationDataProcessingRepositoryTest.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

MODBULKOPS-281 - 500 error when Keep editing clicked multiple times
On a larger data set, when user clicks keep editing button multiple times before the the Are you sure form is populated, 500 error occurs and the user needs to start over.
* Changed structure of entity and table wich is root cause of the error
* Updated other code realted to the entity. …

MODBULKOPS-281 - 500 error when Keep editing clicked multiple times

---

src/main/java/org/folio/bulkops/service/ErrorService.java
src/main/java/org/folio/bulkops/service/RecordUpdateService.java
src/main/java/org/folio/bulkops/util/Constants.java
src/main/java/org/folio/bulkops/util/EntityPathResolver.java
src/test/java/org/folio/bulkops/service/ErrorServiceTest.java
src/test/java/org/folio/bulkops/service/RecordUpdateServiceTest.java
src/test/java/org/folio/bulkops/util/EntityPathResolverTest.java

[MODBULKOPS-256](https://folio-org.atlassian.net/browse/MODBULKOPS-256) - Provide User-friendly Error Message for Optimistic Locking in Downloaded Errors
Follow-up PR to [#205](https://github.com/folio-org/mod-bulk-operations/pull/205/) with support entity link in parameters.
Ideally all of the PRs involved in breaking changes would be merged in the same …

MODBULKOPS-256 - Provide User-friendly Error Message for Optimistic Locking in Downloaded Errors

---

src/main/resources/db/changelog/changes/24-05-2024_drop_id_column_bulk_operation_data_processing.sql

MODBULKOPS-292 - clear table before ddl execution
Clear table bulk_operation_data_processing before changing it structure.
Migration script shouldn't break deployment. …

MODBULKOPS-292 - clear table before ddl execution

---

descriptors/ModuleDescriptor-template.json

[MODBULKOPS-289](https://folio-org.atlassian.net/browse/MODBULKOPS-289)
Increased holding-storage version to be synchronized with inventory-storage module 
Increased holding-storage version from 6.0 to 7.0 …

MODBULKOPS-289 -  increased holding-storage version from 6.0 to 7.0

---

src/main/java/org/folio/bulkops/service/DataExportJobUpdateService.java
src/main/java/org/folio/bulkops/service/EntityTypeService.java
src/main/java/org/folio/bulkops/service/PreviewService.java
src/main/java/org/folio/bulkops/util/EntityPathResolver.java
src/main/java/org/folio/bulkops/util/UpdateOptionTypeToFieldResolver.java
src/main/java/org/folio/bulkops/util/Utils.java
src/main/resources/db/changelog/changes/18-06-2024_updates_for_editing_marc.sql
src/main/resources/swagger.api/schemas/entity_type.json
src/test/java/org/folio/bulkops/repository/BulkOperationMarcRuleRepositoryTest.java
src/test/java/org/folio/bulkops/service/PreviewServiceTest.java
src/test/java/org/folio/bulkops/service/RecordUpdateServiceTest.java
src/test/java/org/folio/bulkops/util/EntityPathResolverTest.java

[MODBULKOPS-255](https://folio-org.atlassian.net/browse/MODBULKOPS-255) - MARC Instance - Content Update request for MARC instances
Provide functionality to work with MARC content updates
* Minor improvements
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …

MODBULKOPS-255 - MARC Instance - Content Update request for MARC instances

---

descriptors/ModuleDescriptor-template.json

MODBULKOPS-204 add missed permissions

---

src/main/java/org/folio/bulkops/domain/bean/PreferredEmailCommunication.java
src/main/java/org/folio/bulkops/domain/converter/PreferredEmailCommunicationConverter.java

[MODBULKOPS-305](https://folio-org.atlassian.net/browse/MODBULKOPS-305) - User schema updating - new field preferredEmailCommunication
* Minor fixes …

MODBULKOPS-305 - User schema updating - new field preferredEmailCommunication

---

src/main/java/org/folio/bulkops/processor/MarcInstanceDataProcessor.java
src/main/resources/swagger.api/schemas/marc_subfield_action.json
src/test/java/org/folio/bulkops/processor/MarcInstanceDataProcessorTest.java

[MODBULKOPS-243](https://folio-org.atlassian.net/browse/MODBULKOPS-243) - MARC Instance - Add New Field
Provide a way for library staff to add note fields to the existing SRS record
* Implemented logic …

MODBULKOPS-243 - MARC Instance - Add New Field

---

src/main/java/org/folio/bulkops/processor/MarcInstanceDataProcessor.java
src/main/java/org/folio/bulkops/util/Constants.java
src/test/java/org/folio/bulkops/processor/MarcInstanceDataProcessorTest.java

[MODBULKOPS-274](https://folio-org.atlassian.net/browse/MODBULKOPS-274) - MARC Instance - Remove all
Provide a way for library staff to remove notes from the existing note field in the existing SRS record.
Add option. …

MODBULKOPS-274 - MARC Instance - Remove all

---

src/main/java/org/folio/bulkops/processor/MarcInstanceDataProcessor.java
src/test/java/org/folio/bulkops/processor/MarcInstanceDataProcessorTest.java

[MODBULKOPS-245](https://folio-org.atlassian.net/browse/MODBULKOPS-245) - MARC Instance - Find and Remove Field or Subfield
Provide a way for library staff to remove notes from the existing note field in the existing SRS record.
* Implemented logic …

MODBULKOPS-245 - MARC Instance - Find and Remove Field or Subfield

---

src/main/java/org/folio/bulkops/controller/BulkOperationController.java
src/test/java/org/folio/bulkops/controller/BulkOperationControllerTest.java

[MODBULKOPS-248](https://folio-org.atlassian.net/browse/MODBULKOPS-248) - MARC Instance - Download MARC Preview
Provide a way to preview in MARC format of the changes before they are committed to the database.
* Implemented download preview logic …

MODBULKOPS-248 - MARC Instance - Download MARC Preview

---

src/main/java/org/folio/bulkops/service/ErrorService.java
src/main/java/org/folio/bulkops/service/MarcToUnifiedTableRowMapper.java
src/main/java/org/folio/bulkops/service/PreviewService.java
src/main/java/org/folio/bulkops/util/Constants.java
src/test/java/org/folio/bulkops/service/ErrorServiceTest.java

[MODBULKOPS-303](https://folio-org.atlassian.net/browse/MODBULKOPS-303) - Error accordion disappears after refreshing the page
The error accordion is disappeared after CANCEL during bulk edit and then refreshing the page.
* Fixed preview logic
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

MODBULKOPS-303 - Error accordion disappears after refreshing the page

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/client/DataImportClient.java
src/main/java/org/folio/bulkops/client/DataImportProfilesClient.java
src/main/java/org/folio/bulkops/client/MetadataProviderClient.java
src/main/java/org/folio/bulkops/domain/bean/ActionProfile.java
src/main/java/org/folio/bulkops/domain/bean/ActionProfilePost.java
src/main/java/org/folio/bulkops/domain/bean/FileDefinition.java
src/main/java/org/folio/bulkops/domain/bean/JobExecution.java
src/main/java/org/folio/bulkops/domain/bean/JobExecutionCollection.java
src/main/java/org/folio/bulkops/domain/bean/JobProfile.java
src/main/java/org/folio/bulkops/domain/bean/JobProfileCollection.java
src/main/java/org/folio/bulkops/domain/bean/JobProfileInfo.java
src/main/java/org/folio/bulkops/domain/bean/JobProfilePost.java
src/main/java/org/folio/bulkops/domain/bean/JournalRecord.java
src/main/java/org/folio/bulkops/domain/bean/JournalRecordCollection.java
src/main/java/org/folio/bulkops/domain/bean/MappingProfile.java
src/main/java/org/folio/bulkops/domain/bean/MappingProfilePost.java
src/main/java/org/folio/bulkops/domain/bean/MatchProfile.java
src/main/java/org/folio/bulkops/domain/bean/MatchProfilePost.java
src/main/java/org/folio/bulkops/domain/bean/ProfileAssociations.java
src/main/java/org/folio/bulkops/domain/bean/UploadFileDefinition.java
src/main/java/org/folio/bulkops/domain/bean/UploadFileDefinitionProcessFiles.java

[MODBULKOPS-312](https://folio-org.atlassian.net/browse/MODBULKOPS-312) - Data Import client …

MODBULKOPS-312 - Data Import client

---

src/main/java/org/folio/bulkops/domain/bean/Item.java
src/main/java/org/folio/bulkops/domain/converter/ItemElectronicAccessListConverter.java
src/main/java/org/folio/bulkops/service/ElectronicAccessHelper.java
src/main/java/org/folio/bulkops/service/ElectronicAccessService.java
src/test/resources/files/complete_item.json

[MODBULKOPS-204](https://folio-org.atlassian.net/browse/MODBULKOPS-204)
Currently the list of column names for item records is ordered almost randomly and it includes properties that are important for backend processes but are normally not exposed in the inventory UI. …

MODBULKOPS-204 - Item record's column names cleanup

---

src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/java/org/folio/bulkops/service/DataExportJobUpdateService.java
src/main/java/org/folio/bulkops/util/ErrorCode.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

[MODBULKOPS-308](https://folio-org.atlassian.net/browse/MODBULKOPS-308) - Investigate a better way to notify about S3 connectivity issues. …

MODBULKOPS-308 -  Investigate a better way to notify about S3 connectivity issues.

---

src/main/java/org/folio/bulkops/processor/HoldingsDataProcessor.java
src/main/java/org/folio/bulkops/processor/InstanceUpdateProcessor.java
src/main/java/org/folio/bulkops/processor/ItemDataProcessor.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/java/org/folio/bulkops/service/HoldingsReferenceHelper.java
src/main/java/org/folio/bulkops/service/HoldingsReferenceService.java
src/test/java/org/folio/bulkops/processor/HoldingsDataProcessorTest.java
src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java
src/test/java/org/folio/bulkops/processor/UpdateProcessorTest.java

[MODBULKOPS-324](https://folio-org.atlassian.net/browse/MODBULKOPS-324) - 404 Not Found error on Confirmation screen when bulk edit Items via Central tenant
The issue was found on large dataset. When do bulk edit of ~100K Items records then part of records (~6K) goes to “Errors“ on Confirmation screen with the following reason:
358e5d69-3d86-5d15-b443-febe5f0585c2,[404 Not Found] during [GET] to [[http://holdings-storage/holdings/215a1215-722b-56e8-92e5-8974c9f70ae3]](http://holdings-storage/holdings/215a1215-722b-56e8-92e5-8974c9f70ae3%5D) [HoldingsClient#getHoldingById(String)]: [Not found]
Add tenant id where cache is used.
- Does this …

MODBULKOPS-324  - 404 Not Found error on Confirmation screen when bulk edit Items via Central tenant

---

descriptors/ModuleDescriptor-template.json

[MODBULKOPS-328](https://folio-org.atlassian.net/browse/MODBULKOPS-328) - Update bulk-edit interface version
bulk-edit interface version should be updated to 4.0
* Updated interface version
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …

MODBULKOPS-328 - Update bulk-edit interface version

---

src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/resources/swagger.api/schemas/query-request.json
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

[MODBULKOPS-331](https://folio-org.atlassian.net/browse/MODBULKOPS-331) - Optimisation of FQM query invocation
To avoid double execution of FQM Query bulk operation service (/bulk-operations/query) should be refactored to retrieve query execution result by queryId instead of making second call to FQM.
* Removed redundant logic
Ideally …

MODBULKOPS-331 - Optimisation of FQM query invocation

---

src/main/java/org/folio/bulkops/processor/FolioInstanceDataProcessor.java

[MODBULKOPS-290](https://folio-org.atlassian.net/browse/MODBULKOPS-290) - 422 Unprocessable Entity error for MARC instances with Instance notes
When MARC Instances are bulk edited with actions related to Instance notes - the error “Bulk edit of instance notes is not supported for MARC Instances“ is expected for such Instances.
In some cases when actions are applied to the Instance notes that particular MARC Instance has in addition to expected error the 422 Unprocessable Entity error appears and prevents other bulk edit actions not related to Instance notes (e.g. suppress from discovery, staff suppress). Such cases are:
Change note type within the group
Mark as staff only
Find and replace
* Fixed instance clone logic
Before merging this PR, please go through the following list and take …

MODBULKOPS-290 - 422 Unprocessable Entity error for MARC instances with Instance notes

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/client/MetadataProviderClient.java
src/main/java/org/folio/bulkops/client/SrsClient.java
src/main/java/org/folio/bulkops/domain/bean/ExternalIdsHolder.java
src/main/java/org/folio/bulkops/domain/bean/JobLogEntry.java
src/main/java/org/folio/bulkops/domain/bean/JobLogEntryCollection.java
src/main/java/org/folio/bulkops/domain/bean/SrsRecord.java
src/main/java/org/folio/bulkops/exception/DataImportException.java
src/main/java/org/folio/bulkops/service/ErrorService.java
src/test/java/org/folio/bulkops/service/ErrorServiceTest.java

[MODBULKOPS-313](https://folio-org.atlassian.net/browse/MODBULKOPS-313) - Importing errors processing
Data import errors should be retrieved from Data Import  and transformed to Bulk Operation format.
Use srs client to get identifier. …

MODBULKOPS-313 - Importing errors processing

---

src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/java/org/folio/bulkops/service/ErrorService.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

[MODBULKOPS-345](https://folio-org.atlassian.net/browse/MODBULKOPS-345) - Holdings fail to be bulk edited from Central tenant
Fixing issue with bulk operation job failing.
Prevent tenant switching for saving errors. …

MODBULKOPS-345 - Holdings fail to be bulk edited from Central tenant

---

descriptors/ModuleDescriptor-template.json

[MODBULKOPS-358](https://folio-org.atlassian.net/browse/MODBULKOPS-358) - Add permissions to specify bulk-edit operations
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

MODBULKOPS-358 - update module descriptor with permissions

---

src/main/java/org/folio/bulkops/processor/MarcInstanceUpdateProcessor.java
src/test/java/org/folio/bulkops/processor/MarcInstanceUpdateProcessorTest.java

[MODBULKOPS-249](https://folio-org.atlassian.net/browse/MODBULKOPS-249) - MARC Instance - Confirmation screen (MarcInstanceUpdateProcessor)
* Fixed split file disabled flow
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODBULKOPS-249 - MARC Instance - Confirmation screen (MarcInstanceUpdateProcessor)

---

src/main/java/org/folio/bulkops/processor/UserUpdateProcessor.java

[MODBULKOPS-314](https://folio-org.atlassian.net/browse/MODBULKOPS-314) - Central tenant edit permissions handling …

MODBULKOPS-314 - write permission validation for user

---

src/main/java/org/folio/bulkops/domain/bean/Subject.java

[MODBULKOPS-351](https://folio-org.atlassian.net/browse/MODBULKOPS-351) - Synchronize data used for bulk edit of MARC fields between “Bulk edit“ and “Inventory“ apps
Synchronize data used for bulk edit of MARC fields between “Bulk edit“ and “Inventory“ based on the existing SRS mappings
* Fixed subject fields
Ideally all of the PRs involved in breaking …

MODBULKOPS-351 - Synchronize data used for bulk edit of MARC fields between “Bulk edit“ and “Inventory“ apps

---

descriptors/ModuleDescriptor-template.json

MODBULKOPS-249 add missed permission for MARC download

---

descriptors/ModuleDescriptor-template.json

MODBULKOPS-363 MODBULKOPS-374 API version update

---

pom.xml

[FOLIO-4087](https://folio-org.atlassian.net/browse/FOLIO-4087) - RMB & spring-base upgrades
Updating RMB dependency according to https://github.com/folio-org/raml-module-builder/blob/v35.3.0/doc/upgrading.md#version-353
Updating dependencies, apply requirements from https://github.com/folio-org/raml-module-builder/blob/v35.3.0/doc/upgrading.md#version-353.
- Do PRs exist for these …

FOLIO-4087 - RMB & spring-base upgrades

---

src/main/java/org/folio/bulkops/domain/bean/UserTenant.java
src/main/java/org/folio/bulkops/processor/HoldingsUpdateProcessor.java
src/main/java/org/folio/bulkops/processor/ItemUpdateProcessor.java
src/main/java/org/folio/bulkops/processor/note/CsvDownloadPreProcessor.java
src/main/java/org/folio/bulkops/service/ConsortiaService.java
src/main/java/org/folio/bulkops/service/PreviewService.java
src/main/java/org/folio/bulkops/service/RecordUpdateService.java
src/main/java/org/folio/bulkops/service/TenantTableUpdater.java
src/test/java/org/folio/bulkops/processor/note/CsvDownloadPreProcessorTest.java
src/test/java/org/folio/bulkops/service/ConsortiaServiceTest.java
src/test/java/org/folio/bulkops/service/TenantTableUpdaterTest.java

[MODBULKOPS-360](https://folio-org.atlassian.net/browse/MODBULKOPS-360) - Include Tentant in columns selection …

MODBULKOPS-360 - Include Tentant in columns selection

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/service/PreviewService.java

[MODBULKOPS-334](https://folio-org.atlassian.net/browse/MODBULKOPS-334) - Preventing record update with values from different tenants 
Fix NPE for non-ecs, increase minor (previous changes).
Check tenant note pairs for null. …

MODBULKOPS-334 - Preventing record update with values from different tenants 

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/domain/bean/ChildInstance.java
src/main/java/org/folio/bulkops/domain/bean/Dates.java
src/main/java/org/folio/bulkops/domain/bean/Instance.java
src/main/java/org/folio/bulkops/domain/bean/ParentInstance.java
src/test/java/org/folio/bulkops/service/OpenCSVConverterTest.java
src/test/resources/files/bad_data_instance.json
src/test/resources/files/instance.json

[MODBULKOPS-350](https://folio-org.atlassian.net/browse/MODBULKOPS-350) - API version update
Aligning instances schema relative to mod-inventory API. …

MODBULKOPS-350 - Aligning instances schema relative to mod-inventory API

---

README.md
descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/client/EurekaUserPermissionsClient.java
src/main/java/org/folio/bulkops/client/OkapiUserPermissionsClient.java
src/main/java/org/folio/bulkops/controller/BulkOperationController.java
src/main/java/org/folio/bulkops/domain/bean/UserPermissions.java
src/main/java/org/folio/bulkops/processor/permissions/check/PermissionEnum.java
src/main/java/org/folio/bulkops/processor/permissions/check/PermissionsValidator.java
src/main/java/org/folio/bulkops/processor/permissions/check/RequiredPermissionResolver.java
src/main/java/org/folio/bulkops/service/UserPermissionsService.java
src/main/resources/application.yml
src/test/java/org/folio/bulkops/processor/permissions/check/PermissionsValidatorTest.java
src/test/java/org/folio/bulkops/processor/permissions/check/RequiredPermissionResolverTest.java
src/test/java/org/folio/bulkops/service/UserPermissionsServiceTest.java
src/test/resources/application.yml

[MODBULKOPS-384](https://folio-org.atlassian.net/browse/MODBULKOPS-384) - Support Eureka permissions model for bulk operations (write operations)
Implement logic to support permissions from mod-roles-keycloak and integrate it in existing approach
Introduce an environment variable in the module configuration that will be specifically depend to the environment to switch logic between mod-permissions and mod-roles-keycloak.
- Are the …

MODBULKOPS-384 - Support Eureka permissions model for bulk operations (write operations)

---

descriptors/ModuleDescriptor-template.json

[MODBULKOPS-375](https://folio-org.atlassian.net/browse/MODBULKOPS-375) - missing permission
* Added missing permission
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

MODBULKOPS-375 - missing permission

---

descriptors/ModuleDescriptor-template.json

Add consortia interface to module descriptor 
While it's helpful for reviewers to help …

Update module descriptor with consortia interface

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/service/MarcUpdateService.java

[MODBULKOPS-375](https://folio-org.atlassian.net/browse/MODBULKOPS-375) - renamed permission …

MODBULKOPS-375 - Retrieve MARC record from SRS after completion of bulk edit

---

src/main/java/org/folio/bulkops/service/SrsService.java

[MODBULKOPS-393](https://folio-org.atlassian.net/browse/MODBULKOPS-393) - Issues related to display errors from DI on Confirmation screen of bulk edit MARC fields
Minor fix.
Fix minor.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …

MODBULKOPS-393 - Issues related to display errors from DI on Confirmation screen of bulk edit MARC fields

---

descriptors/ModuleDescriptor-template.json

Add missed interface

---

src/main/java/org/folio/bulkops/processor/HoldingsDataProcessor.java
src/test/java/org/folio/bulkops/processor/HoldingsDataProcessorTest.java

[MODBULKOPS-402](https://folio-org.atlassian.net/browse/MODBULKOPS-402) - Issues with bulk edit of URL relationship on non-ECS and ECS environments
Add check for central tenant and remove check for consortia.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication …

MODBULKOPS-402 - Issues with bulk edit of URL relationship on non-ECS and ECS environments

---

src/main/java/org/folio/bulkops/controller/BulkOperationController.java
src/main/java/org/folio/bulkops/util/Constants.java
src/test/java/org/folio/bulkops/controller/BulkOperationControllerTest.java

[MODBULKOPS-412](https://folio-org.atlassian.net/browse/MODBULKOPS-412) - Add UTF-8 BOM to Exported csv Files
When opening a CSV file containing Arabic characters with Microsoft Excel, the Arabic text is not displayed correctly. Instead, strange or unreadable characters are shown.
UTF-8 BOM: Byte sequence EF BB BF (hexadecimal) to be added at the start of the file
- Do PRs exist for these …

MODBULKOPS-412 -  Add UTF-8 BOM to Exported csv Files

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/domain/bean/HoldingsRecordsSource.java
src/main/java/org/folio/bulkops/processor/HoldingsDataProcessor.java
src/main/java/org/folio/bulkops/service/ErrorService.java
src/main/java/org/folio/bulkops/service/HoldingsReferenceService.java
src/test/java/org/folio/bulkops/processor/HoldingsDataProcessorTest.java
src/test/java/org/folio/bulkops/service/ErrorServiceTest.java
src/test/java/org/folio/bulkops/service/HoldingsReferenceHelperTest.java

Release 2.1.3

---

src/main/resources/import/profiles/mapping_profile_update_instance.json

[MODBULKOPS-424](https://folio-org.atlassian.net/browse/MODBULKOPS-424) - Check Data import profile creation and update mod bulk operation data import job profile …

MODBULKOPS-424 - Check Data import profile creation and update mod bulk operation data import job profile

---

src/main/java/org/folio/bulkops/service/MarcUpdateService.java
src/main/java/org/folio/bulkops/service/SrsService.java
src/test/java/org/folio/bulkops/service/MarcUpdateServiceTest.java
src/test/java/org/folio/bulkops/service/SrsServiceTest.java

[MODBULKOPS-423](https://folio-org.atlassian.net/browse/MODBULKOPS-423) - For bulk edit of MARC Instances file with changed records is available for downloading before commit completes
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …

MODBULKOPS-423 - For bulk edit of MARC Instances file with changed records is available for downloading before commit completes

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/domain/bean/GetParsedRecordsBatchRequestBody.java
src/main/java/org/folio/bulkops/service/MarcUpdateService.java
src/main/java/org/folio/bulkops/service/SrsService.java
src/main/resources/import/profiles/mapping_profile_update_instance.json
src/test/java/org/folio/bulkops/service/MarcUpdateServiceTest.java
src/test/java/org/folio/bulkops/service/SrsServiceTest.java

Release 2.1.4

---

src/main/java/org/folio/bulkops/client/DataImportClient.java
src/main/java/org/folio/bulkops/processor/MarcInstanceUpdateProcessor.java
src/test/java/org/folio/bulkops/processor/MarcInstanceUpdateProcessorTest.java

[MODDATAIMP-1124](https://folio-org.atlassian.net/browse/MODDATAIMP-1124) - Bulk edit MARC flow fails to commit by User, works only by Admin for single records
Switching fileDefinitionId parameter to uploadDefinitionId in uploadFileDefinitionsProcessFiles-method.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

MODDATAIMP-1124 - Bulk edit MARC flow fails to commit by User, works only by Admin for single records

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/bulkops/controller/BulkOperationController.java
src/main/java/org/folio/bulkops/processor/permissions/check/PermissionsProvider.java
src/main/java/org/folio/bulkops/processor/permissions/check/PermissionsValidator.java

Release 2.1.5

---

pom.xml

[MODBULKOPS-440](https://folio-org.atlassian.net/browse/MODBULKOPS-440) - Upgrade vulnerable dependencies for Ramsons
Upgrade dependencies …

MODBULKOPS-440 - Upgrade vulnerable dependencies for Ramsons

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/client/DataImportClient.java
src/main/java/org/folio/bulkops/domain/bean/Instance.java
src/main/java/org/folio/bulkops/processor/MarcInstanceUpdateProcessor.java
src/main/java/org/folio/bulkops/service/MarcUpdateService.java
src/main/java/org/folio/bulkops/service/PreviewService.java
src/test/java/org/folio/bulkops/processor/MarcInstanceUpdateProcessorTest.java
src/test/java/org/folio/bulkops/service/MarcUpdateServiceTest.java

Release 2.1.6

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/client/RemoteFileSystemClient.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/java/org/folio/bulkops/service/MarcRemoteStorageWriter.java
src/main/java/org/folio/bulkops/service/MarcUpdateService.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

Release 2.1.7

---

pom.xml

[MODBULKOPS-449](https://folio-org.atlassian.net/browse/MODBULKOPS-449) - Query search failed in Bulk Operations
Fixing issue in bulk operations query approach (due to schemas mismatching).
Update lib-fqm-query-processor version to align EntityDataType schema in FQM and BulkOps.
Ideally all of the PRs involved in breaking changes would be merged in the …

MODBULKOPS-449 - Query search failed in Bulk Operations

---

src/main/java/org/folio/bulkops/service/ListUsersService.java
src/test/java/org/folio/bulkops/service/ListUsersServiceTest.java

[BF-992](https://folio-org.atlassian.net/browse/BF-992) - "Something went wrong" error appears and list of Users is empty in Bulk edit app on Eureka environment
Not a fix, but optimization. Replacement of requesting each user by id by one query request.
Replacement couple of requests /users?query=id==<id>&limit=1 by one request  /users?query=id==(<id_1> or <id_2> or ... <id_n>)&limit=n
- …

BF-992 - Users retrieving optimization

---

src/test/java/org/folio/bulkops/service/DataImportJobCompletionReceiverServiceTest.java

[MODBULKOPS-459](https://folio-org.atlassian.net/browse/MODBULKOPS-459) - TD: fix unstable testReceiveJobExecutionUpdate unit test
It is necessary to fix the unit test DataImportJobCompletionReceiverServiceTest.testReceiveJobExecutionUpdate, which periodically causes build failures in mod-bulk-operations build.
Unit test refactoring.
Ideally all of the PRs …

MODBULKOPS-459 - TD: fix unstable testReceiveJobExecutionUpdate unit test

---

src/main/java/org/folio/bulkops/service/BulkOperationService.java

[MODBULKOPS-406](https://folio-org.atlassian.net/browse/MODBULKOPS-406) - Handling Data Import notification
Follow-up PR to [PR#335](https://github.com/folio-org/mod-bulk-operations/pull/335) with fix for statistics refreshing regression issue.
Revert removed logic for statistics refreshing of bulk operation during retrieving bulk operation.
Ideally all of …

MODBULKOPS-406 - Handling Data Import notification

---

src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java

[MODBULKOPS-428](https://folio-org.atlassian.net/browse/MODBULKOPS-428) - Apply changes - MARC Bib records with administrative data
* Minor improvements …

MODBULKOPS-428 - Apply changes - MARC Bib records with administrative data

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/controller/BulkOperationController.java
src/main/java/org/folio/bulkops/service/ListUsersService.java
src/test/java/org/folio/bulkops/service/ListUsersServiceTest.java

Release 2.1.9 includes optimizations for a new platform.

Release 2.1.9

---

descriptors/ModuleDescriptor-template.json

Add missed interfaces

---

src/main/java/org/folio/bulkops/service/ListUsersService.java

BF-992 fix users retrieving

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/bulkops/service/ListUsersService.java

Release 2.1.10

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/service/BulkOperationService.java

* fixed redundant data import result processing calls

Release 2.1.11

---

src/main/java/org/folio/bulkops/service/ErrorService.java
src/test/java/org/folio/bulkops/service/ErrorServiceTest.java

[MODBULKOPS-451](https://folio-org.atlassian.net/browse/MODBULKOPS-451) - Rework errors preview
Follow-up PR to [PR#353](https://github.com/folio-org/mod-bulk-operations/pull/353)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

MODBULKOPS-451 - Rework errors preview

---

descriptors/ModuleDescriptor-template.json

MODBULKOPS-454 add missed permissions for tenant API to support system user creation

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/bulkops/client/SrsClient.java
src/main/resources/permissions/system-user-permissions.csv
src/test/java/org/folio/bulkops/service/ErrorServiceTest.java

[MODBULKOPS-454](https://folio-org.atlassian.net/browse/MODBULKOPS-454) -  Issue with data-import.splitconfig.get
Fix issue with data-import.splitconfig.get permission absence.
Using system user approach [folio-spring-system-use](https://github.com/folio-org/folio-spring-support/tree/master/folio-spring-system-user).
Ideally all of the PRs involved in …

MODBULKOPS-454 - Issue with data-import.splitconfig.get

---

src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/05-02-2025_add_migration_script_for_warnings.sql
src/main/resources/db/changelog/changes/05-02-2025_add_migration_script_for_warnings.xml

[MODEXPW-547](https://folio-org.atlassian.net/browse/MODEXPW-547) - Provide error and warnings for matched records
Add migration script for matched warnings.
Add migration script for matched warnings. …

MODEXPW-547 - Provide error and warnings for matched records

---

src/main/resources/permissions/system-user-permissions.csv

Add inventory-storage.contributor-types.collection.get to system user.
While it's helpful …

SYSTEM USER PERMISSION

---

descriptors/ModuleDescriptor-template.json

MODBULKOPS-448 add missed permissions

---

descriptors/ModuleDescriptor-template.json

Add missed permissions

---

src/main/java/org/folio/bulkops/service/Marc21ReferenceProvider.java

[MODBULKOPS-390](https://folio-org.atlassian.net/browse/MODBULKOPS-390) - Previewing bulk edit changes
* added force visibility for instance languages …

MODBULKOPS-390 - Previewing bulk edit changes

---

src/main/java/org/folio/bulkops/processor/folio/FolioInstanceUpdateProcessor.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/java/org/folio/bulkops/service/ErrorService.java
src/main/java/org/folio/bulkops/service/MarcUpdateService.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java
src/test/java/org/folio/bulkops/service/ErrorServiceTest.java
src/test/java/org/folio/bulkops/service/MarcUpdateServiceTest.java
src/test/resources/files/instance_marc.json

[MODBULKOPS-429](https://folio-org.atlassian.net/browse/MODBULKOPS-429) - Commit changes - MARC Bib records with administrative data
* Fixed download links of committed records
* Fixed error message issues …

MODBULKOPS-429 - Commit changes - MARC Bib records with administrative data

---

src/main/java/org/folio/bulkops/service/DataExportJobUpdateService.java

MODBULKOPS-20 ignore matched file if not present

---

src/main/java/org/folio/bulkops/service/MarcToUnifiedTableRowMapperHelper.java
src/test/java/org/folio/bulkops/service/MarcToUnifiedTableRowMapperHelperTest.java
src/test/java/org/folio/bulkops/service/PreviewServiceTest.java

[MODBULKOPS-396](https://folio-org.atlassian.net/browse/MODBULKOPS-396) - Punctionation is truncated from the note text
To avoid truncation of punctuation in note text.
Update instances preview processing. …

MODBULKOPS-396 - Punctuation is truncated from the note text

---

src/main/java/org/folio/bulkops/processor/folio/AdministrativeNotesUpdater.java
src/main/java/org/folio/bulkops/processor/folio/HoldingsNotesUpdater.java
src/main/java/org/folio/bulkops/processor/folio/InstanceNotesUpdaterFactory.java
src/main/java/org/folio/bulkops/processor/folio/ItemsNotesUpdater.java
src/test/java/org/folio/bulkops/processor/FolioInstanceDataProcessorTest.java
src/test/java/org/folio/bulkops/processor/HoldingsDataProcessorTest.java
src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java

[MODBULKOPS-455](https://folio-org.atlassian.net/browse/MODBULKOPS-455) - Modify "Remove" action followed by “Find” action on Bulk edit form for Inventory records to remove part of the text
“Find” action  should be modified to remove only partial match.
* Updated FIND-REMOVE logic
Ideally all of the PRs involved in breaking changes …

MODBULKOPS-455 - Modify "Remove" action followed by “Find” action on Bulk edit form for Inventory records to remove part of the text

---

src/main/java/org/folio/bulkops/processor/folio/ElectronicAccessUpdaterFactory.java
src/main/java/org/folio/bulkops/service/BulkOperationService.java
src/main/java/org/folio/bulkops/service/MetadataProviderService.java
src/main/java/org/folio/bulkops/util/MarcCsvHelper.java
src/test/java/org/folio/bulkops/processor/HoldingsDataProcessorTest.java
src/test/java/org/folio/bulkops/service/BulkOperationServiceTest.java
src/test/resources/files/instance_marc_filtered.json

[MODBULKOPS-475](https://folio-org.atlassian.net/browse/MODBULKOPS-475) - Data Import completion event and log entries availability synchronization
* Minor improvements …

MODBULKOPS-475 - Data Import completion event and log entries availability synchronization

---

src/main/java/org/folio/bulkops/service/InstanceReferenceService.java

MODBULKOPS-247 encode instance types requests

---

NEWS.md
pom.xml

[MODBULKOPS-489](https://folio-org.atlassian.net/browse/MODBULKOPS-489) - Release 2.2.0

MODBULKOPS-489 - Release 2.2.0

---

NEWS.md
pom.xml

Release 2.2.1.
Release v2.2.1.
While it's helpful for reviewers to help identify potential …

Release 2.2.1

---

README.md

Upgrading readme with memory configuration.
While it's helpful for reviewers to help …

Memory configuration: readme upgrading

---

src/main/java/org/folio/bulkops/util/MarcCsvHelper.java

[MODBULKOPS-189](https://folio-org.atlassian.net/browse/MODBULKOPS-189)  - Electronic access Columns for Instance Records in Preview and Are you sure? Forms
Fix CSV file in Are u sure? form.
Update position of notes and electronic access in CSV.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …

MODBULKOPS-189 - Adding Electronic access Columns for Instance Records in Preview and Are you sure? Forms

---

src/main/java/org/folio/bulkops/domain/converter/SubjectListConverter.java
src/main/java/org/folio/bulkops/service/MarcToUnifiedTableRowMapper.java
src/test/java/org/folio/bulkops/service/MarcToUnifiedTableRowMapperTest.java

[MODBULKOPS-189](https://folio-org.atlassian.net/browse/MODBULKOPS-189)  - Electronic access Columns for Instance Records in Preview and Are you sure? Forms
Fix CSV file in Are u sure? form.
Add heading to CSV file, remove them from preview. Fix white spaces.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …

MODBULKOPS-189 - Electronic access Columns for Instance Records in Preview and Are you sure? Forms

---

NEWS.md
pom.xml
src/main/resources/permissions/system-user-permissions.csv

Release 2.2.2

---

src/main/java/org/folio/bulkops/service/BulkOperationService.java

[MODBULKOPS-507](https://folio-org.atlassian.net/browse/MODBULKOPS-507) - Unexpected end of stream error  - non-ECS
Extend logging to identify issue …

MODBULKOPS-507 - Unexpected end of stream error  - non-ECS

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/service/BulkOperationService.java

Release 2.2.3

---

src/main/java/org/folio/bulkops/service/PreviewService.java

Follow-up PR to [PR#401](https://github.com/folio-org/mod-bulk-operations/pull/401) to support and handle preview generating for Subjects and SubColumns for Subjects.

MODBULKOPS-190 - Adding Subject Column for Instance Records in Preview and Are you sure? Forms

---

src/main/java/org/folio/bulkops/service/MarcToUnifiedTableRowMapperHelper.java
src/test/java/org/folio/bulkops/service/MarcToUnifiedTableRowMapperHelperTest.java

[MODBULKOPS-191](https://folio-org.atlassian.net/browse/MODBULKOPS-191) - Adding Classification Columns for Instance Records in Preview and Are you sure? Forms
* Minor improvements in classification processing logic …

MODBULKOPS-191 - Adding Classification Columns for Instance Records in Preview and Are you sure? Forms

---

src/main/java/org/folio/bulkops/domain/bean/Instance.java

Align instance schema (deleted field)

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/bulkops/domain/bean/Instance.java

Release 2.2.4

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/service/EntityTypeService.java
src/test/java/org/folio/bulkops/service/EntityTypeServiceTest.java

Release v2.1.13 (Ramsons)
While it's helpful for reviewers to help identify potential …

Release 2.1.13

---

src/main/java/org/folio/bulkops/service/MarcToUnifiedTableRowMapperHelper.java
src/test/java/org/folio/bulkops/service/MarcToUnifiedTableRowMapperHelperTest.java
src/test/java/org/folio/bulkops/service/PreviewServiceTest.java

https://folio-org.atlassian.net/browse/MODBULKOPS-187

fixing issues in publication record

---

src/main/java/org/folio/bulkops/domain/entity/Profile.java
src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/changes/05-29-2025_add_profile_table.sql
src/main/resources/db/changelog/changes/05-29-2025_add_profile_table.xml
src/main/resources/swagger.api/schemas/profile.json

created sql script for the profile table, added json schema and created entity as well

MODBULKOPS-517 - Profile schema creation

---

src/main/java/org/folio/bulkops/domain/bean/Personal.java
src/main/resources/swagger.api/examples/unified_table.sample

MODBULKOPS-337 fix date of birth column name

---

src/main/java/org/folio/bulkops/service/ElectronicAccessReferenceService.java

MODBULKOPS-337 fix electronic access rel error name

---

src/main/java/org/folio/bulkops/batch/JobCompletionNotificationListener.java
src/test/java/org/folio/bulkops/batch/JobCompletionNotificationListenerTest.java

[MODBULKOPS-336](https://folio-org.atlassian.net/browse/MODBULKOPS-336) - Stage 3a - FQM Integration (identifiers): switching matched records flow to use mod-bulk-operations capabilities
Fix usedTenants for ECS.
Populate usedTenants after job is completed from json matched.
Ideally all of the PRs involved in breaking changes would be merged in the same day …

MODBULKOPS-336 - Stage 3a - FQM Integration (identifiers): switching matched records flow to use mod-bulk-operations capabilities

---

.github/dependabot.yml

MODBULKOPS-521 setup dependabot

---

NEWS.md
pom.xml
src/main/java/org/folio/bulkops/domain/bean/CirculationNote.java
src/test/java/org/folio/bulkops/processor/ItemDataProcessorTest.java

Release v2.1.15 (Ramsons).
While it's helpful for reviewers to help identify potential …

Release v2.1.15 (Ramsons)

---

src/main/java/org/folio/bulkops/processor/marc/MarcFlowCommitProcessor.java
src/main/java/org/folio/bulkops/util/FolioExecutionContextUtil.java

[MODBULKOPS-516](https://folio-org.atlassian.net/browse/MODBULKOPS-516) - FAILED (UNKNOWN) in Electronic access, Subject, Classification columns in .csv file with updated records
* Improved context setting logic …

MODBULKOPS-516 - FAILED (UNKNOWN) in Electronic access, Subject, Classification columns in .csv file with updated records

---

src/main/java/org/folio/bulkops/domain/bean/Item.java

The order did not change after bulk Edit

MODBULKOPS-553: adjust item schema

---

src/main/java/org/folio/bulkops/domain/bean/AdditionalCallNumber.java
src/main/java/org/folio/bulkops/domain/bean/HoldingsRecord.java
src/main/java/org/folio/bulkops/domain/bean/Instance.java
src/main/java/org/folio/bulkops/domain/bean/Item.java

[MODBULKOPS-555](https://folio-org.atlassian.net/browse/MODBULKOPS-555) - Instance, Holdings, Item schemas updating - new fields
In order to support new fields introduced in Trillium schema should be updated:
* Update Instance schema
* Update Holdings schema
* Update Item schema
* Update business logic operating with Instance, Holdings, Item entities to support new fields
* Updated entities' schemas
- Are the JIRAs under active …

MODBULKOPS-555 - Instance, Holdings, Item schemas updating - new fields
